# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "rundbcan_cazymeannotation"
description: CAZyme annotation module for the dbcan pipeline. This module is used
  to annotate carbohydrate-active enzymes (CAZymes) from genomic data using the dbCAN
  annotation tool.
keywords:
  - dbCAN
  - download
  - CAZyme
  - CAZyme gene Cluster
  - genomes
tools:
  - "dbcan":
      description: "Standalone version of dbCAN annotation tool for automated CAZyme
        annotation."
      homepage: "https://run-dbcan-new.readthedocs.io/en/latest/"
      documentation: "https://run-dbcan-new.readthedocs.io/en/latest/"
      tool_dev_url: "https://github.com/bcb-unl/run_dbcan_new/"
      doi: "10.1093/nar/gkad328"
      licence: ["GPL v3-or-later"]
      identifier: biotools:dbcan

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - input_raw_data:
        type: file
        description: FASTA file for protein sequences.
        pattern: "*.{fasta,fa,faa}"
  - - dbcan_db:
        type: directory
        description: Path to the dbCAN database directory.
output:
  - cazyme_annotation:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - ${prefix}_dbcan_cazyme/overview.tsv:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
  - dbcanhmm_results:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - ${prefix}_dbcan_cazyme/dbCAN_hmm_results.tsv:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
  - dbcansub_results:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - ${prefix}_dbcan_cazyme/dbCANsub_hmm_results.tsv:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
  - dbcandiamond_results:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - ${prefix}_dbcan_cazyme/diamond.out:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@Xinpeng021001"
maintainers:
  - "@Xinpeng021001"
